if ("${ANDROID_NDK_HOME}" STREQUAL "")
	message(FATAL_ERROR "Fatal: ANDROID_NDK_HOME is not valid.")
endif()

set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION ${CFG_ANDROID_SDK})


#set(CMAKE_ANDROID_NDK "${ANDROID_NDK_HOME}")
#set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang)
#set(CMAKE_ANDROID_ARCH_ABI ${CFG_TARGET_ABI})
#set(CMAKE_ANDROID_STL_TYPE c++_static)
#set(CMAKE_ANDROID_API ${CFG_ANDROID_SDK})
set(ANDROID_TOOLCHAIN clang)
set(ANDROID_ABI ${CFG_TARGET_ABI})
set(ANDROID_PLATFORM ${CFG_ANDROID_SDK})
set(ANDROID_STL c++_static)
set(CMAKE_TOOLCHAIN_FILE "${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake")
set(CMAKE_ANDROID_STANDALONE_TOOLCHAIN ${CFG_ANDROID_TOOLCHAIN_PATH})

#set(CMAKE_C_COMPILER_FORCED TRUE)
#set(CMAKE_CXX_COMPILER_FORCED TRUE)

#list(APPEND CMAKE_SHARED_LINKER_FLAGS " -Wl,--no-undefined")

